#!/usr/bin/env python3
"""carparts_remap.py — fold Ultralytics Carparts-Seg's 23 classes onto the FOUR
labels this pipeline actually consumes, and write a YOLO-seg dataset for it.

Why a remap at all: seg_masks.py emits masks for glass / wheel / lamp only.
seg_project.py treats BODY as the default label (0) and INTERIOR as the *unseen*
label (4) derived from the depth pass — interior is geometric, never a mask
class. So the four trainable labels are body, glass, wheel, lamp.

WHAT THE SOURCE TAXONOMY CANNOT EXPRESS (measured, see CARPARTS_SEG.md):
  * there is NO side-window class. Only back_glass and front_glass exist, so
    side glazing is either unlabelled or swallowed by the door polygons, which
    map to BODY. Training on this actively teaches "side window = body".
  * there is no roof, wing, quarter-panel or sill class. Harmless — body is the
    default label — but it means "body" here means "the panels someone wanted
    to price for damage", not "the car's shell".
  * there is nothing for interior, which is fine: we never wanted it from 2D.

--symmetric folds the left/right lamp and door variants onto their generic
class, which the source annotates inconsistently (front_light appears in 53.2%
of train images, front_left_light in 13.1% — the same object under two schemas).

Run: python3 carparts_remap.py <src_root> <dst_root>
"""
import os
import shutil
import sys

SRC_NAMES = {
    0: "back_bumper", 1: "back_door", 2: "back_glass", 3: "back_left_door",
    4: "back_left_light", 5: "back_light", 6: "back_right_door",
    7: "back_right_light", 8: "front_bumper", 9: "front_door",
    10: "front_glass", 11: "front_left_door", 12: "front_left_light",
    13: "front_light", 14: "front_right_door", 15: "front_right_light",
    16: "hood", 17: "left_mirror", 18: "object", 19: "right_mirror",
    20: "tailgate", 21: "trunk", 22: "wheel",
}

# our labels, in seg_project.py's own order (BODY=0, GLASS=1, WHEEL=2, LAMP=3)
OURS = {"body": 0, "glass": 1, "wheel": 2, "lamp": 3}
MAP = {
    "back_bumper": "body", "back_door": "body", "back_left_door": "body",
    "back_right_door": "body", "front_bumper": "body", "front_door": "body",
    "front_left_door": "body", "front_right_door": "body", "hood": "body",
    "tailgate": "body", "trunk": "body",
    "back_glass": "glass", "front_glass": "glass",
    "wheel": "wheel",
    "back_left_light": "lamp", "back_light": "lamp", "back_right_light": "lamp",
    "front_left_light": "lamp", "front_light": "lamp",
    "front_right_light": "lamp",
    # dropped: mirrors have no counterpart label in seg_project, and "object"
    # is a 10-instance junk class (0.3% of train images).
    "left_mirror": None, "right_mirror": None, "object": None,
}

YAML = """# generated by carparts_remap.py — Carparts-Seg folded onto our 4 labels
path: {root}
train: images/train
val: images/val
test: images/test
names:
  0: body
  1: glass
  2: wheel
  3: lamp
"""


def remap(src, dst):
    stats = {k: 0 for k in OURS}
    dropped = 0
    for split in ("train", "val", "test"):
        si, sl = os.path.join(src, "images", split), os.path.join(src, "labels", split)
        di, dl = os.path.join(dst, "images", split), os.path.join(dst, "labels", split)
        os.makedirs(di, exist_ok=True)
        os.makedirs(dl, exist_ok=True)
        for fn in os.listdir(sl):
            out = []
            for ln in open(os.path.join(sl, fn)):
                p = ln.split()
                if not p:
                    continue
                tgt = MAP[SRC_NAMES[int(p[0])]]
                if tgt is None:
                    dropped += 1
                    continue
                stats[tgt] += 1
                out.append(" ".join([str(OURS[tgt])] + p[1:]))
            open(os.path.join(dl, fn), "w").write("\n".join(out) + ("\n" if out else ""))
            stem = os.path.splitext(fn)[0]
            for ext in (".jpg", ".jpeg", ".png"):
                s = os.path.join(si, stem + ext)
                if os.path.exists(s):
                    d = os.path.join(di, stem + ext)
                    if not os.path.exists(d):
                        os.symlink(os.path.abspath(s), d)
                    break
    open(os.path.join(dst, "carparts4.yaml"), "w").write(
        YAML.format(root=os.path.abspath(dst)))
    print("instances per our label:", stats, "| dropped:", dropped)


if __name__ == "__main__":
    remap(sys.argv[1], sys.argv[2])
    print("REMAP_DONE")
