import puppeteer from 'puppeteer-core';
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ROOT=process.argv[2];
const MIME={'.html':'text/html','.wasm':'application/wasm','.js':'text/javascript','.glb':'model/gltf-binary'};
const srv=http.createServer((q,s)=>{const f=path.join(ROOT,q.url==='/'?'golf-bay.html':decodeURIComponent(q.url.split('?')[0]));
  if(!fs.existsSync(f)){s.writeHead(404);return s.end()}
  s.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream','Content-Length':fs.statSync(f).size});
  fs.createReadStream(f).pipe(s)});
await new Promise(r=>srv.listen(8934,'127.0.0.1',r));
const b=await puppeteer.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--window-size=1440,900']});
const p=await b.newPage(); await p.setViewport({width:1440,height:900});
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
p.on('console',m=>{ if(m.type()==='error') errs.push('CONSOLE '+m.text()); });
await p.goto('http://127.0.0.1:8934/',{waitUntil:'load'});
await p.waitForFunction(()=>window.__carReady===true,{timeout:300000,polling:500});
await p.evaluate(()=>document.querySelector('[data-m="doorOff"]').click());
await new Promise(r=>setTimeout(r,2500));
const click=async sel=>{ const found=await p.evaluate(s=>{const e=document.querySelector(s);
  if(!e) return false; e.click(); return true}, sel); if(!found) errs.push('NO BUTTON '+sel);
  await new Promise(r=>setTimeout(r,700)); };
const show=async l=>console.log(l.padEnd(34),JSON.stringify(await p.evaluate(()=>window.__door())));
await show('at start');
console.log('\n--- WRONG ORDER: bolt out first ---');
await click('[data-x="do:bolt_ul"]'); await show('bolt before anything');
console.log('\n--- in order ---');
await click('[data-x="do:look"]');    await show('01 looked up');
await click('[data-x="dotool:1"]');   await show('   picked wrong tool');
await click('[data-x="do:bolt_ul"]'); await show('   bolt w/ wrong tool -> stop');
await click('[data-x="dotool:0"]');   await show('   correct tool');
await click('[data-x="do:loom"]');    await show('   loom w/ battery on -> stop');
await click('[data-x="do:isolate"]'); await show('02 isolated');
await click('[data-x="do:loom"]');    await show('04 loom out');
await click('[data-x="do:bolt_ul"]'); await show('   bolt, strap still on -> stop');
await click('[data-x="do:strap"]');   await show('05 strap released');
await click('[data-x="do:bolt_ul"]'); await show('   bolt, no support -> stop');
await click('[data-x="do:support"]'); await show('03 supported');
await click('[data-x="do:mark"]');    await show('06 marked');
await p.screenshot({path:process.argv[3]+'/dooroff_ready.png'});
for (const k of ['bolt_ul','bolt_ll','bolt_bl','bolt_bb']) await click(`[data-x="do:${k}"]`);
await show('all 4 bolts out');
await click('[data-x="do:lift"]'); await new Promise(r=>setTimeout(r,1400));
await show('lifted away');
await p.screenshot({path:process.argv[3]+'/dooroff_done.png'});
console.log('\nerrors:', errs.length?errs:'none');
await b.close(); srv.close();
