"""Plan a split-and-balanced training corpus as an INDEX, not as copied pixels.

WHY AN INDEX AND NOT A COPY
---------------------------
The real corpus is ~14GB and there is ~5GB of free disk. Balancing a severely
imbalanced detection set by physically writing augmented copies of images would
need several times the corpus size, so it simply cannot be done here. It is also
the worse engineering: a directory of half a million JPEGs is opaque, slow to
re-derive, and impossible to audit after the fact.

So this tool writes a PLAN. It emits, per training sample, which original image
it comes from, which split it belongs to, which repeat number it is, and which
named augmentation recipe the loader should apply on the fly. One copy of the
pixels stays on disk; the balance is expressed in a few megabytes of JSONL that
can be diffed, reviewed and regenerated byte-for-byte from a seed.

THE ORDER OF OPERATIONS IS THE WHOLE POINT: SPLIT FIRST, BALANCE SECOND
----------------------------------------------------------------------
Augmenting before splitting is the easiest way to build a dataset that reports a
wonderful score and has learned nothing. Twelve augmented copies of one
photograph are near-identical; if the split is drawn afterwards, copies of the
same source land in train AND in validation, so the model is validated against
pictures it has memorised. This corpus already suffered exactly that failure
once — 26.6% of an earlier version had annotation boxes burned into the pixels,
the leak was present in the validation split too, and the resulting 0.4390 mAP
was a measurement of the contamination rather than of the model. A second,
self-inflicted version of that mistake is not worth making.

So:
  1. pool every source directory and dedupe by SHA-256 of the image bytes
  2. split the ORIGINALS per class, 80/10/10, deterministically
  3. repeat + augment ONLY the train split, up to the per-class target
  4. leave valid and test real, unbalanced and un-augmented

An unbalanced validation set is not a defect. It measures the world. A balanced,
augmented one measures itself.

DETERMINISM
-----------
Originals are sorted by their image `sha` and then shuffled with a seeded RNG,
one independent RNG stream per class, so the same command always produces the
same split and adding a new class does not reshuffle the existing ones. No
timestamps are written into any output file, because the guarantee this tool
makes is that two runs with the same seed are byte-identical.

STRATIFICATION WITH MULTI-LABEL IMAGES
--------------------------------------
Most images carry boxes of several classes, so "split per class" needs a rule
for which class owns an image. The rule is: the RAREST class present in the
image owns it. Rare classes are the ones a bad split ruins — a class with 67
images cannot afford to have its handful of validation images drawn by luck —
so the scarcest signal in each image decides its stratum, and every class gets a
true 80/10/10 spread of the images that contain it.

AUGMENTATION RECIPES ARE NAMES, NOT PIXELS
------------------------------------------
The index records e.g. ["hflip"] or ["crop", "photometric"]. It never opens an
image to transform it. The training loader owns the implementation.

Only BOX-SAFE operations are listed: horizontal flip, crop-and-resize,
photometric jitter (brightness / contrast / saturation), and mild blur or
sharpen. Each has an exact bounding-box transform, or none at all.

Two further flags sit OUTSIDE the recipe cycle, `wm` and `sn` — synthetic
watermark and grain/recompression. They are outside it on purpose. A recipe is
chosen by repeat number, so recipe frequency follows how heavily a class was
repeated, and a rare class that got twelve copies would carry a different
augmentation mix from a common class that got one. For ordinary augmentation
that is harmless. For these two it would be fatal, because their entire job is
to be UNCORRELATED WITH THE CLASS: they exist to stop the network reading
"Dreamstime tiling" as "smashed windscreen", a shortcut that is genuinely
present in this corpus because stock agencies over-supply dramatic damage. So
they are drawn per sample from the image sha alone, at a fixed rate, and land
on every class equally. Nothing is discarded for being watermarked; the mark is
made uninformative instead. See watermark_aug.py.

FREE ROTATION IS DELIBERATELY EXCLUDED — DO NOT ADD IT. Rotating an image means
re-fitting an axis-aligned rectangle around a rotated box, which inflates every
box slightly. Applied a dozen times over to drag a thin class up to its target,
that bias is no longer slight: it teaches the detector that damage regions are
systematically larger than they are, and a scratch detector that over-claims its
extent prices a repair wrongly. It is left out on purpose, not by oversight.

OUTPUTS (all in --out)
----------------------
  index.jsonl    one line per training SAMPLE: split, image_id, sha, rep,
                 recipe, seed. Train samples are ordered by repeat number, so
                 every original appears once before any appears twice.
  images.jsonl   one line per unique ORIGINAL image: sha, file, size, split,
                 owning class, and its boxes in normalised [x, y, w, h].
  classes.json   class index (0 reserved as the COCO placeholder), per-class
                 colour and canonical taxonomy id, all from class_map.py.
  plan.json      the balance report: per class real / target / achieved /
                 effective multiplier, plus every flag raised.

USAGE
-----
    python build_train_index.py --coco /home/user/cardata_damage \\
        --out /tmp/idx --target-per-class 4000 --max-repeat 15
    python build_train_index.py --coco DIR --report-only
    python build_train_index.py --coco DIR --selftest
"""
import argparse
import hashlib
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import class_map as CM

SPLIT_FRACTIONS = (("train", 0.80), ("valid", 0.10), ("test", 0.10))
IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".bmp")

# Every op here has an exact box transform (or leaves boxes untouched entirely).
# See the module docstring for why rotation is not in this table.
BOX_SAFE_OPS = ("hflip", "crop", "photometric", "blur", "sharpen")

# The recipe cycle. Repeat k of an image takes RECIPES[(k - 1) % len(RECIPES)],
# so an image collects distinct recipes before it ever collects a duplicate one,
# and the per-sample `seed` re-rolls the loader's random parameters even then.
RECIPES = (
    ["hflip"],
    ["crop"],
    ["photometric"],
    ["hflip", "crop"],
    ["hflip", "photometric"],
    ["crop", "photometric"],
    ["blur"],
    ["hflip", "crop", "photometric"],
    ["sharpen"],
    ["crop", "blur"],
    ["hflip", "sharpen"],
    ["hflip", "crop", "blur"],
)

# Above this, a class is not being balanced, it is being cloned. Reported rather
# than silently applied.
UNHEALTHY_MULTIPLIER = 15.0

# Fraction of TRAIN samples that get a synthetic agency-style watermark, and a
# grain/recompression pass, stamped on regardless of class. Nothing is deleted
# for carrying a real watermark; instead the mark is made statistically useless
# (watermark_aug.py has the argument and the measurement). Roughly half is the
# efficient choice: it maximises the entropy of the mark, so knowing whether an
# image is marked tells the network as close to nothing as arithmetic allows.
WM_RATE = 0.50
SOURCE_NOISE_RATE = 0.35


# ---------------------------------------------------------------- ingest ----

def sha256_file(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(chunk), b""):
            h.update(b)
    return h.hexdigest()


def find_coco_files(root):
    """Every COCO annotation file under `root`, sorted for determinism.

    A Roboflow-shaped export puts one `_annotations.coco.json` in each of
    train/ valid/ test/. Those directories are treated purely as SOURCES: the
    split they encode is discarded and re-derived here, because a split
    inherited from an upstream export carries whatever leakage the upstream
    export had.
    """
    hits = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        for fn in sorted(filenames):
            if fn == "_annotations.coco.json":
                hits.append(os.path.join(dirpath, fn))
    if not hits:
        for fn in sorted(os.listdir(root)):
            if not fn.lower().endswith(".json"):
                continue
            p = os.path.join(root, fn)
            try:
                with open(p) as f:
                    d = json.load(f)
            except Exception:
                continue
            if isinstance(d, dict) and {"images", "annotations",
                                        "categories"} <= set(d):
                hits.append(p)
    return hits


# Set by build() when --merge-groups is given. Module-level rather than
# threaded through every call because resolve_class is reached from several
# places and a half-grouped corpus — some boxes grouped, some not — would be
# far worse than either choice made consistently.
GROUPED = False


def resolve_class(name):
    """Source category name -> final training class, or None if not trained.

    Already-final names (the merged corpus writes them straight out) are
    accepted first; anything else goes through class_map's source lookups.
    When GROUPED, the result is folded into its training group, so balance
    comes from merging related damage rather than from cloning thin classes.
    """
    n = str(name).strip()
    final = n if n in CM.FINAL_CLASSES else CM.resolve(n)
    if final and GROUPED:
        return CM.group_for(final)
    return final


def load_originals(root, sha_cache_path=None, verbose=True):
    """Every unique original image under `root`, with its boxes.

    Returns (images, stats). Each image is
        {sha, file (relative to root), abspath, width, height,
         boxes: [(cls, x, y, w, h) normalised], counts: {cls: n}}
    """
    cache = {}
    if sha_cache_path and os.path.exists(sha_cache_path):
        try:
            with open(sha_cache_path) as f:
                cache = json.load(f)
        except Exception:
            cache = {}

    stats = {"coco_files": 0, "images_seen": 0, "images_missing_file": 0,
             "images_no_boxes": 0, "boxes_seen": 0, "boxes_dropped_bad": 0,
             "boxes_dropped_untrained": 0, "duplicate_shas": 0,
             "untrained_categories": {}}
    by_sha = {}

    for coco_path in find_coco_files(root):
        stats["coco_files"] += 1
        img_dir = os.path.dirname(coco_path)
        with open(coco_path) as f:
            doc = json.load(f)

        cats = {}
        for c in doc.get("categories", []):
            final = resolve_class(c.get("name", ""))
            if final:
                cats[c["id"]] = final
            elif str(c.get("name", "")).strip() != "_placeholder_":
                key = str(c.get("name", ""))
                stats["untrained_categories"][key] = \
                    stats["untrained_categories"].get(key, 0)

        anns_by_img = {}
        for a in doc.get("annotations", []):
            anns_by_img.setdefault(a.get("image_id"), []).append(a)

        for im in doc.get("images", []):
            stats["images_seen"] += 1
            abspath = os.path.join(img_dir, im.get("file_name", ""))
            if not os.path.isfile(abspath):
                # Roboflow exports keep the JPEGs beside the COCO file, but
                # ingest_roboflow_zips and merge_coco_source write them to an
                # images/ subdirectory. Both layouts are real corpora in this
                # project, so both resolve here rather than one of them being
                # counted as 167,157 missing files.
                alt = os.path.join(img_dir, "images", im.get("file_name", ""))
                if os.path.isfile(alt):
                    abspath = alt
                else:
                    stats["images_missing_file"] += 1
                    continue

            sha = im.get("sha")
            if not sha:
                st = os.stat(abspath)
                ck = f"{abspath}|{st.st_size}|{int(st.st_mtime)}"
                sha = cache.get(ck)
                if not sha:
                    sha = sha256_file(abspath)
                    cache[ck] = sha

            W = float(im.get("width") or 0) or None
            H = float(im.get("height") or 0) or None
            if not W or not H:
                from PIL import Image
                with Image.open(abspath) as pim:
                    W, H = float(pim.width), float(pim.height)

            boxes = []
            for a in anns_by_img.get(im.get("id"), []):
                stats["boxes_seen"] += 1
                cls = cats.get(a.get("category_id"))
                if not cls:
                    stats["boxes_dropped_untrained"] += 1
                    continue
                bb = a.get("bbox") or []
                if len(bb) != 4:
                    stats["boxes_dropped_bad"] += 1
                    continue
                try:
                    x, y, w, h = (float(v) for v in bb)
                except (TypeError, ValueError):
                    stats["boxes_dropped_bad"] += 1
                    continue
                if w <= 0 or h <= 0:
                    stats["boxes_dropped_bad"] += 1
                    continue
                # Clamp to the frame, then normalise. Normalised boxes are the
                # convention the rest of this product already uses (overlay.py,
                # detect.py), so the index needs no translation layer.
                x0 = min(max(x, 0.0), W)
                y0 = min(max(y, 0.0), H)
                x1 = min(max(x + w, 0.0), W)
                y1 = min(max(y + h, 0.0), H)
                if x1 - x0 <= 0 or y1 - y0 <= 0:
                    stats["boxes_dropped_bad"] += 1
                    continue
                boxes.append([cls, round(x0 / W, 6), round(y0 / H, 6),
                              round((x1 - x0) / W, 6), round((y1 - y0) / H, 6)])

            if not boxes:
                stats["images_no_boxes"] += 1
                continue

            counts = {}
            for b in boxes:
                counts[b[0]] = counts.get(b[0], 0) + 1
            rec = {"sha": sha,
                   "file": os.path.relpath(abspath, root),
                   "abspath": abspath,
                   "width": int(W), "height": int(H),
                   "boxes": boxes, "counts": counts}

            prev = by_sha.get(sha)
            if prev is None:
                by_sha[sha] = rec
            else:
                stats["duplicate_shas"] += 1
                # Identical pixels under two paths. Keep the richer annotation,
                # break ties on path so the choice is reproducible.
                if (len(rec["boxes"]), rec["file"]) > (len(prev["boxes"]),
                                                       prev["file"]):
                    by_sha[sha] = rec

    if sha_cache_path:
        try:
            with open(sha_cache_path, "w") as f:
                json.dump(cache, f)
        except Exception:
            pass

    images = sorted(by_sha.values(), key=lambda r: r["sha"])
    return images, stats


# ----------------------------------------------------------------- split ----

def owning_class(rec, global_box_counts):
    """The RAREST class present in an image owns it for splitting purposes.

    See the module docstring: rare classes are the ones a careless split
    destroys, so the scarcest thing in the frame chooses the stratum. Ties break
    on the class name, so the choice never depends on dict ordering.
    """
    present = sorted(rec["counts"])
    return min(present, key=lambda c: (global_box_counts.get(c, 0), c))


def split_sizes(n):
    """80/10/10 counts for n originals, with small classes handled explicitly.

    Rounding alone gives a 6-image class zero validation images, which is a
    silent hole rather than a small one. Any class with at least three images
    yields one to valid and one to test, and says so by construction.
    """
    if n <= 0:
        return 0, 0, 0
    if n == 1:
        return 1, 0, 0
    if n == 2:
        return 1, 1, 0
    n_valid = int(round(n * SPLIT_FRACTIONS[1][1]))
    n_test = int(round(n * SPLIT_FRACTIONS[2][1]))
    n_valid = max(1, n_valid)
    n_test = max(1, n_test)
    while n - n_valid - n_test < 1:
        if n_test >= n_valid:
            n_test -= 1
        else:
            n_valid -= 1
    return n - n_valid - n_test, n_valid, n_test


def split_originals(images, seed, train_only=None):
    """Assign every original to exactly one split. Mutates `images` in place.

    `train_only` is a set of shas barred from valid and test — images carrying
    a burned-in annotation, per clean_dataset.VERDICT_POLICY. They are useful
    training material and harmless there, but an evaluation image with its own
    label printed on it lets the model score by reading, and the number that
    comes back would be measuring OCR rather than damage detection.

    They are sorted to the FRONT of each class before the split boundary is
    drawn, so they fill train from the start and the train/valid/test SIZES are
    completely unchanged. Excluding them from the eval pool without doing this
    would silently shrink valid and test.
    """
    train_only = train_only or set()
    global_box_counts = {}
    for rec in images:
        for c, n in rec["counts"].items():
            global_box_counts[c] = global_box_counts.get(c, 0) + n

    strata = {}
    for rec in images:
        rec["owner"] = owning_class(rec, global_box_counts)
        strata.setdefault(rec["owner"], []).append(rec)

    per_class_split = {}
    for cls in sorted(strata):
        rows = sorted(strata[cls], key=lambda r: r["sha"])
        # One RNG stream per class, keyed by the class name, so the split of one
        # class does not move when another class gains or loses images.
        random.Random(f"{seed}:{cls}").shuffle(rows)
        n_tr, n_va, n_te = split_sizes(len(rows))
        if train_only:
            # Stable partition: pinned images keep their shuffled order, so a
            # class with none of them splits byte-identically to before.
            pinned = [r for r in rows if r["sha"] in train_only]
            rest = [r for r in rows if r["sha"] not in train_only]
            if len(pinned) > n_tr:
                # More pinned images than train can hold. Silently spilling
                # them into valid is exactly the leak this exists to stop, so
                # the overflow is dropped from the build and reported instead.
                for r in pinned[n_tr:]:
                    r["split"] = "excluded"     # never emitted, never counted
                pinned = pinned[:n_tr]
                rows = pinned + rest
                n_tr, n_va, n_te = split_sizes(len(rows))
            else:
                rows = pinned + rest
        for i, rec in enumerate(rows):
            rec["split"] = ("train" if i < n_tr else
                            "valid" if i < n_tr + n_va else "test")
        per_class_split[cls] = {"train": n_tr, "valid": n_va, "test": n_te,
                                "total": len(rows)}
    return per_class_split, global_box_counts


# --------------------------------------------------------------- balance ----

def count_units(recs, reps, unit):
    """{class: count} over a set of samples, in boxes or in images."""
    out = {}
    for rec in recs:
        r = reps.get(rec["sha"], 1)
        for c, n in rec["counts"].items():
            out[c] = out.get(c, 0) + (n * r if unit == "boxes" else r)
    return out


def balance_train(train_recs, target, max_repeat, unit,
                  unhealthy=UNHEALTHY_MULTIPLIER):
    """Decide how many times each TRAIN original repeats.

    Rarest class first, because a rare class has the fewest images to work with
    and every repeat it triggers also lifts whatever else shares the frame — so
    doing it in that order means the common classes need fewer repeats of their
    own. Within a class, repeats are handed out in full passes over its image
    pool: every original is used a second time before any is used a third.

    Returns (reps, report).
    """
    reps = {rec["sha"]: 1 for rec in train_recs}
    by_sha = {rec["sha"]: rec for rec in train_recs}

    real = count_units(train_recs, {s: 1 for s in reps}, unit)
    pools = {}
    for rec in train_recs:
        for c in rec["counts"]:
            pools.setdefault(c, []).append(rec["sha"])
    for c in pools:
        pools[c] = sorted(set(pools[c]))

    current = dict(real)
    order = sorted(real, key=lambda c: (real[c], c))
    capped = {}

    for cls in order:
        pool = pools.get(cls, [])
        if not pool or current.get(cls, 0) >= target:
            continue
        for _pass in range(2, max_repeat + 1):
            moved = False
            for sha in pool:
                if current.get(cls, 0) >= target:
                    break
                if reps[sha] >= max_repeat:
                    continue
                reps[sha] += 1
                moved = True
                for c, n in by_sha[sha]["counts"].items():
                    current[c] = current.get(c, 0) + (n if unit == "boxes" else 1)
            if current.get(cls, 0) >= target or not moved:
                break
        if current.get(cls, 0) < target:
            capped[cls] = True

    report = {}
    flags = []
    for cls in sorted(real):
        r = real[cls]
        ach = current.get(cls, 0)
        required = (target / r) if r else float("inf")
        row = {
            "real": r,
            "target": target,
            "achieved": ach,
            "effective_multiplier": round(ach / r, 3) if r else None,
            "required_multiplier": round(required, 3) if r else None,
            "train_images": len(pools.get(cls, [])),
            "max_repeat_used": max((reps[s] for s in pools.get(cls, [])),
                                   default=0),
            "reached_target": ach >= target,
            "capped_by_max_repeat": bool(capped.get(cls)),
            "unhealthy": bool(r) and required > unhealthy,
        }
        if row["unhealthy"]:
            flags.append(
                f"UNHEALTHY: {cls} would need {required:.1f}x to reach "
                f"{target} {unit} from {r} real — above the {unhealthy:.0f}x "
                f"ceiling. That is cloning, not balancing: collect more "
                f"{cls} data or lower --target-per-class.")
        if row["capped_by_max_repeat"]:
            flags.append(
                f"CAPPED: {cls} stopped at {ach}/{target} {unit} because "
                f"--max-repeat {max_repeat} was reached. Not silently "
                f"exceeded.")
        report[cls] = row

    return reps, report, flags


# ---------------------------------------------------------------- output ----

def sample_seed(sha, rep):
    """Per-sample RNG seed so two repeats sharing a recipe name still differ in
    the loader's random parameters (crop window, jitter strength)."""
    return (int(sha[:8], 16) ^ ((rep + 1) * 2654435761)) & 0xFFFFFFFF


def _bernoulli(sha, rep, salt, rate):
    """Deterministic coin drawn from image content only — never from class.

    That independence is the whole mechanism (see watermark_aug.py): a feature
    present at the same rate in every class carries no information about the
    class, so the network cannot use it as a shortcut. If this draw were ever
    conditioned on the label, it would MANUFACTURE the correlation it exists to
    destroy, so it takes the sha and nothing else.
    """
    h = int(hashlib.sha256(f"{salt}:{sha}:{rep}".encode()).hexdigest()[:8], 16)
    return (h / 0xFFFFFFFF) < rate


def mark_flags(sha, rep, split):
    """(watermark, source_noise) for one sample.

    Train only. Valid and test stay exactly as they arrived — the measurement
    has to be taken on real pixels, and an augmented validation set measures
    the augmentation.
    """
    if split != "train":
        return False, False
    return (_bernoulli(sha, rep, "wm", WM_RATE),
            _bernoulli(sha, rep, "sn", SOURCE_NOISE_RATE))


def build_samples(images, reps):
    """The full sample list, train ordered by repeat number.

    Ordering train by rep means a sequential reader consumes every original once
    before it sees a single augmented copy — the "use every original before you
    reuse any" guarantee, visible in the file itself rather than asserted in a
    comment.
    """
    out = []
    train = sorted([r for r in images if r["split"] == "train"],
                   key=lambda r: r["sha"])
    max_rep = max((reps.get(r["sha"], 1) for r in train), default=1)
    for rep in range(max_rep):
        for rec in train:
            if reps.get(rec["sha"], 1) <= rep:
                continue
            recipe = [] if rep == 0 else list(RECIPES[(rep - 1) % len(RECIPES)])
            wm, sn = mark_flags(rec["sha"], rep, "train")
            out.append({"split": "train", "sha": rec["sha"],
                        "file": rec["file"], "rep": rep, "recipe": recipe,
                        "wm": wm, "sn": sn,
                        "seed": sample_seed(rec["sha"], rep)})
    for split in ("valid", "test"):
        for rec in sorted([r for r in images if r["split"] == split],
                          key=lambda r: r["sha"]):
            # Never repeated, never augmented. This is the honest measurement.
            out.append({"split": split, "sha": rec["sha"], "file": rec["file"],
                        "rep": 0, "recipe": [], "wm": False, "sn": False,
                        "seed": sample_seed(rec["sha"], 0)})
    return out


def classes_document(global_box_counts, images):
    """classes.json — index, colour and canonical id, all from class_map."""
    img_counts = {}
    for rec in images:
        for c in rec["counts"]:
            img_counts[c] = img_counts.get(c, 0) + 1

    # Under --merge-groups the model's vocabulary IS the group set, so
    # classes.json must describe groups. Emitting the six ungrouped classes
    # here while training four would put labels.txt out of step with the
    # weights, which is the exact failure prepare_data.py warns about: every
    # prediction mislabelled while the run looks perfectly healthy.
    if GROUPED:
        spec = {g: dict(v, members=list(v["members"]))
                for g, v in CM.TRAIN_GROUPS.items()}
    else:
        spec = {n: dict(v, members=[n]) for n, v in CM.FINAL_CLASSES.items()}
    idx = {name: i + 1 for i, name in enumerate(sorted(spec))}

    rows = []
    for name in sorted(spec):
        d = spec[name]
        rows.append({
            "name": name,
            "index": idx[name],
            "colour": d["colour"],
            "canonical": d["canonical"],
            "members": d["members"],
            "structural": bool(d.get("structural")),
            "boxes_in_corpus": global_box_counts.get(name, 0),
            "images_in_corpus": img_counts.get(name, 0),
            "present": name in global_box_counts,
        })
    return {
        "reserved_index_0": "_placeholder_ (COCO convention; real classes "
                            "start at 1, matching prepare_data.py)",
        "classes": rows,
        "name_to_index": {r["name"]: r["index"] for r in rows},
        "index_to_name": {str(r["index"]): r["name"] for r in rows},
    }


def write_outputs(out_dir, samples, images, classes_doc, plan):
    os.makedirs(out_dir, exist_ok=True)
    # Taken FROM classes_doc, not recomputed from class_map. Under
    # --merge-groups the vocabulary is the group set, and a second independent
    # derivation here is exactly how images.jsonl ends up numbering classes
    # differently from the labels.txt the model is trained against.
    idx = classes_doc["name_to_index"]

    with open(os.path.join(out_dir, "index.jsonl"), "w") as f:
        for s in samples:
            f.write(json.dumps(s, sort_keys=True) + "\n")

    with open(os.path.join(out_dir, "images.jsonl"), "w") as f:
        for rec in sorted(images, key=lambda r: r["sha"]):
            f.write(json.dumps({
                "sha": rec["sha"], "file": rec["file"], "split": rec["split"],
                "width": rec["width"], "height": rec["height"],
                "owner_class": rec["owner"],
                "boxes": [[idx[b[0]], b[1], b[2], b[3], b[4]]
                          for b in rec["boxes"]],
                "box_format": "cls_id,x,y,w,h normalised 0-1",
            }, sort_keys=True) + "\n")

    with open(os.path.join(out_dir, "classes.json"), "w") as f:
        json.dump(classes_doc, f, indent=2, sort_keys=True)
        f.write("\n")

    with open(os.path.join(out_dir, "plan.json"), "w") as f:
        json.dump(plan, f, indent=2, sort_keys=True)
        f.write("\n")


# ---------------------------------------------------------------- report ----

def format_report(plan):
    p = plan
    L = []
    L.append("=" * 78)
    L.append(f"corpus          {p['root']}")
    L.append(f"seed            {p['seed']}   unit={p['unit']}   "
             f"target={p['target_per_class']}   max_repeat={p['max_repeat']}")
    st = p["ingest"]
    L.append(f"coco files      {st['coco_files']}")
    L.append(f"originals       {p['n_originals']} unique "
             f"(seen {st['images_seen']}, dup sha {st['duplicate_shas']}, "
             f"missing file {st['images_missing_file']}, "
             f"no usable boxes {st['images_no_boxes']})")
    L.append(f"boxes           {p['n_boxes']} kept of {st['boxes_seen']} "
             f"(bad {st['boxes_dropped_bad']}, "
             f"untrained class {st['boxes_dropped_untrained']})")
    if st["untrained_categories"]:
        L.append(f"                untrained categories: "
                 f"{sorted(st['untrained_categories'])}")
    L.append("")
    L.append("SPLIT (originals only, 80/10/10, stratified by rarest class "
             "present)")
    L.append(f"  {'class':<16}{'total':>7}{'train':>8}{'valid':>8}{'test':>7}")
    for cls in sorted(p["split_by_owner"]):
        s = p["split_by_owner"][cls]
        L.append(f"  {cls:<16}{s['total']:>7}{s['train']:>8}"
                 f"{s['valid']:>8}{s['test']:>7}")
    tot = p["split_totals"]
    L.append(f"  {'ALL':<16}{tot['total']:>7}{tot['train']:>8}"
             f"{tot['valid']:>8}{tot['test']:>7}")
    L.append("")
    L.append(f"BALANCE (train split only; valid and test stay real and "
             f"un-augmented). Unit: {p['unit']}.")
    L.append(f"  {'class':<16}{'real':>9}{'target':>9}{'achieved':>10}"
             f"{'eff x':>8}{'req x':>8}{'imgs':>7}{'maxrep':>8}  flag")
    for cls in sorted(p["balance"]):
        b = p["balance"][cls]
        flag = ("UNHEALTHY" if b["unhealthy"] else
                "capped" if b["capped_by_max_repeat"] else
                "ok" if b["reached_target"] else "short")
        L.append(f"  {cls:<16}{b['real']:>9}{b['target']:>9}"
                 f"{b['achieved']:>10}{b['effective_multiplier']:>8.2f}"
                 f"{b['required_multiplier']:>8.2f}{b['train_images']:>7}"
                 f"{b['max_repeat_used']:>8}  {flag}")
    L.append("")
    L.append(f"train samples   {p['n_samples']['train']} "
             f"({p['n_samples']['train_originals']} originals + "
             f"{p['n_samples']['train_augmented']} augmented repeats)")
    L.append(f"valid samples   {p['n_samples']['valid']}  (0 augmented)")
    L.append(f"test samples    {p['n_samples']['test']}  (0 augmented)")
    if p["flags"]:
        L.append("")
        L.append("FLAGS")
        for fl in p["flags"]:
            L.append(f"  ! {fl}")
    else:
        L.append("")
        L.append("FLAGS           none — every class reached target within "
                 "the multiplier ceiling.")
    L.append("=" * 78)
    return "\n".join(L)


# ------------------------------------------------------------------ build ---

def load_train_only(path):
    """Read a train-only pin list: bare shas, or jsonl rows with a `sha`.

    Also accepts clean_dataset's own cache format, keeping only the verdicts
    whose policy is "train_only" — so the output of the cleaning pass can be
    handed straight in without an intermediate conversion step.
    """
    if not path:
        return set()
    try:
        from clean_dataset import policy_for
    except Exception:                                       # pragma: no cover
        def policy_for(_v):
            return "train_only"
    out = set()
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith("{"):
                try:
                    r = json.loads(line)
                except ValueError:
                    continue
                sha = r.get("sha")
                if sha and ("verdict" not in r
                            or policy_for(r["verdict"]) == "train_only"):
                    out.add(sha)
            else:
                out.add(line.split()[0])
    return out


def build(root, out_dir, target_per_class=None, max_repeat=15, seed=1337,
          unit="boxes", unhealthy=UNHEALTHY_MULTIPLIER, sha_cache=None,
          report_only=False, verbose=True, train_only=None,
          merge_groups=False):
    """Do the whole thing. Returns (plan, samples, images)."""
    global GROUPED
    GROUPED = bool(merge_groups)
    root = os.path.abspath(root)
    images, stats = load_originals(root, sha_cache, verbose)
    if not images:
        raise SystemExit(f"no usable images found under {root}")

    split_by_owner, global_box_counts = split_originals(images, seed,
                                                       train_only)

    train_recs = [r for r in images if r["split"] == "train"]
    real_train = count_units(train_recs, {r["sha"]: 1 for r in train_recs}, unit)
    if target_per_class is None:
        # Default: level up to whatever the largest class already has, which is
        # the only target that needs no extra data by definition.
        target_per_class = max(real_train.values()) if real_train else 0

    reps, balance, flags = balance_train(train_recs, target_per_class,
                                         max_repeat, unit, unhealthy)
    samples = build_samples(images, reps)

    n_train = sum(1 for s in samples if s["split"] == "train")
    n_train_orig = sum(1 for s in samples
                       if s["split"] == "train" and s["rep"] == 0)
    plan = {
        "root": root,
        "seed": seed,
        "unit": unit,
        "target_per_class": target_per_class,
        "max_repeat": max_repeat,
        "unhealthy_multiplier": unhealthy,
        "recipes": [list(r) for r in RECIPES],
        "box_safe_ops": list(BOX_SAFE_OPS),
        "excluded_ops": ["rotate (inflates boxes on re-fit — see docstring)"],
        "ingest": stats,
        "n_originals": len(images),
        "n_boxes": sum(len(r["boxes"]) for r in images),
        "corpus_boxes_by_class": global_box_counts,
        "split_by_owner": split_by_owner,
        "split_totals": {
            "total": len(images),
            "train": sum(1 for r in images if r["split"] == "train"),
            "valid": sum(1 for r in images if r["split"] == "valid"),
            "test": sum(1 for r in images if r["split"] == "test"),
        },
        "balance": balance,
        "flags": flags,
        "n_samples": {
            "train": n_train,
            "train_originals": n_train_orig,
            "train_augmented": n_train - n_train_orig,
            "valid": sum(1 for s in samples if s["split"] == "valid"),
            "test": sum(1 for s in samples if s["split"] == "test"),
        },
    }

    if not report_only:
        write_outputs(out_dir, samples, images,
                      classes_document(global_box_counts, images), plan)
    return plan, samples, images


# --------------------------------------------------------------- selftest ---

def _dir_digest(d):
    out = {}
    for fn in sorted(os.listdir(d)):
        p = os.path.join(d, fn)
        if os.path.isfile(p):
            out[fn] = sha256_file(p)
    return out


def selftest(root, target_per_class=None, max_repeat=15, seed=1337,
             unit="boxes"):
    """Check the guarantees rather than claim them. Returns True if all pass."""
    import shutil
    import tempfile

    results = []

    def check(name, ok, detail=""):
        results.append((name, bool(ok), detail))
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}"
              f"{('  — ' + detail) if detail else ''}")

    tmp = tempfile.mkdtemp(prefix="train_index_selftest_")
    try:
        a = os.path.join(tmp, "a")
        b = os.path.join(tmp, "b")
        print("selftest: building twice with the same seed ...")
        plan, samples, images = build(root, a, target_per_class, max_repeat,
                                      seed, unit, verbose=False)
        build(root, b, target_per_class, max_repeat, seed, unit, verbose=False)

        # 1. every original in exactly one split
        splits = {}
        for rec in images:
            splits.setdefault(rec["split"], set()).add(rec["sha"])
        union = set()
        overlap = set()
        for s, shas in splits.items():
            overlap |= (union & shas)
            union |= shas
        check("every original appears in exactly one split",
              not overlap and union == {r["sha"] for r in images},
              f"{len(images)} originals, {len(overlap)} in two splits")

        # 2. no sha shared between splits (the leak that produced 0.4390 mAP)
        by_split = {}
        for s in samples:
            by_split.setdefault(s["split"], set()).add(s["sha"])
        cross = ((by_split.get("train", set()) & by_split.get("valid", set()))
                 | (by_split.get("train", set()) & by_split.get("test", set()))
                 | (by_split.get("valid", set()) & by_split.get("test", set())))
        check("no sha appears in more than one split (incl. repeats)",
              not cross, f"{len(cross)} leaked shas")

        # 3. valid and test carry zero augmented entries and zero repeats
        bad_aug = [s for s in samples
                   if s["split"] in ("valid", "test")
                   and (s["recipe"] or s["rep"] != 0)]
        seen = {}
        dupes = 0
        for s in samples:
            if s["split"] in ("valid", "test"):
                k = (s["split"], s["sha"])
                dupes += 1 if k in seen else 0
                seen[k] = 1
        check("valid and test contain zero augmented entries",
              not bad_aug and not dupes,
              f"{len(bad_aug)} augmented, {dupes} repeated")

        # 4. class distribution after balancing matches the target
        bad = []
        for cls, row in plan["balance"].items():
            if row["reached_target"]:
                continue
            # Falling short is only acceptable if the plan SAYS so.
            if not (row["capped_by_max_repeat"] or row["unhealthy"]):
                bad.append(cls)
        check("class distribution reaches target, or is flagged when it "
              "cannot", not bad, f"unexplained shortfalls: {bad or 'none'}")

        # 4b. the achieved numbers are real, recomputed from the emitted index
        counts = {}
        by_sha = {r["sha"]: r for r in images}
        for s in samples:
            if s["split"] != "train":
                continue
            for c, n in by_sha[s["sha"]]["counts"].items():
                counts[c] = counts.get(c, 0) + (n if unit == "boxes" else 1)
        mismatch = {c: (counts.get(c, 0), plan["balance"][c]["achieved"])
                    for c in plan["balance"]
                    if counts.get(c, 0) != plan["balance"][c]["achieved"]}
        check("reported achieved counts match the emitted index",
              not mismatch, str(mismatch or "exact"))

        # 4c. THE DECORRELATION PROPERTY. Synthetic watermarks only neutralise
        #     the real ones if they land on every class at the SAME rate; a
        #     skewed stamp would create exactly the shortcut it is meant to
        #     destroy. Measured per class against WM_RATE, not assumed.
        wm_by_cls, n_by_cls = {}, {}
        for s in samples:
            if s["split"] != "train":
                continue
            for c in by_sha[s["sha"]]["counts"]:
                n_by_cls[c] = n_by_cls.get(c, 0) + 1
                wm_by_cls[c] = wm_by_cls.get(c, 0) + (1 if s["wm"] else 0)
        skew = {}
        for c, n in n_by_cls.items():
            if n < 200:                    # too few to bound meaningfully
                continue
            rate = wm_by_cls[c] / n
            # 4 binomial sigma, so a correct build effectively never trips it
            tol = 4.0 * (WM_RATE * (1 - WM_RATE) / n) ** 0.5
            if abs(rate - WM_RATE) > max(tol, 0.02):
                skew[c] = round(rate, 4)
        rates = {c: round(wm_by_cls[c] / n, 3) for c, n in n_by_cls.items()}
        check(f"watermark rate is class-independent (target {WM_RATE}) {rates}",
              not skew, f"skewed: {skew}")

        # 4d. valid and test must carry no synthetic marks at all, or the
        #     score measures the augmentation rather than the model
        dirty = sum(1 for s in samples
                    if s["split"] != "train" and (s["wm"] or s["sn"]))
        check("valid and test carry zero synthetic marks", dirty == 0,
              f"{dirty} marked eval samples")

        # 4e. train_only pinning: images with a burned-in label must never
        #     reach valid or test, and pinning them must not shrink either.
        all_shas = sorted({r["sha"] for r in images})
        pin = set(all_shas[::7])                 # ~14% of the corpus
        import tempfile as _tf
        with _tf.TemporaryDirectory() as c:
            plan_p, samples_p, images_p = build(
                root, c, target_per_class, max_repeat, seed, unit,
                verbose=False, train_only=pin)
            leaked = [s["sha"] for s in samples_p
                      if s["split"] != "train" and s["sha"] in pin]
            check(f"pinned images never reach valid or test ({len(pin)} pinned)",
                  not leaked, f"{len(leaked)} leaked")
            sz = {k: sum(1 for r in images_p if r["split"] == k)
                  for k in ("train", "valid", "test")}
            sz0 = {k: sum(1 for r in images if r["split"] == k)
                   for k in ("train", "valid", "test")}
            check(f"pinning leaves split sizes unchanged {sz}",
                  sz == sz0, f"{sz} vs {sz0}")
            evalpool = [s for s in samples_p if s["split"] in ("valid", "test")]
            check("eval pool is still non-empty after pinning",
                  len(evalpool) > 0, f"{len(evalpool)}")

        # 4f. --merge-groups must build end to end and stay self-consistent.
        #     It did not: write_outputs re-derived the class index from
        #     class_map instead of taking it from classes.json, so a grouped
        #     build died on KeyError 'surface' AFTER writing a complete
        #     index.jsonl — the failure mode that leaves a half-written output
        #     directory looking plausible.
        with _tf.TemporaryDirectory() as gdir:
            gplan, gsamples, gimages = build(
                root, gdir, target_per_class, max_repeat, seed, unit,
                verbose=False, merge_groups=True)
            with open(os.path.join(gdir, "classes.json")) as fh:
                gcls = json.load(fh)
            names = {r["name"] for r in gcls["classes"]}
            check(f"--merge-groups writes the group vocabulary {sorted(names)}",
                  names == set(CM.TRAIN_GROUPS), str(sorted(names)))
            wrote = sorted(os.listdir(gdir))
            check(f"--merge-groups writes all four outputs {wrote}",
                  wrote == ["classes.json", "images.jsonl", "index.jsonl",
                            "plan.json"], str(wrote))
            valid_ids = set(gcls["name_to_index"].values())
            bad = 0
            with open(os.path.join(gdir, "images.jsonl")) as fh:
                for ln in fh:
                    for bb in json.loads(ln)["boxes"]:
                        if bb[0] not in valid_ids:
                            bad += 1
            check("grouped box class ids all appear in classes.json",
                  bad == 0, f"{bad} unknown ids")
            gowners = {r["owner"] for r in gimages}
            check("grouped owners are group names",
                  gowners <= set(CM.TRAIN_GROUPS), str(sorted(gowners)))
            # grouping must not lose or invent boxes
            n_un = sum(len(r["boxes"]) for r in images)
            n_gr = sum(len(r["boxes"]) for r in gimages)
            check(f"grouping preserves the box count ({n_gr} vs {n_un})",
                  n_gr == n_un, f"{n_gr} vs {n_un}")

        # 5. byte-identical reruns
        da, db = _dir_digest(a), _dir_digest(b)
        check("two runs with the same seed are byte-identical",
              da == db and len(da) == 4,
              f"{len(da)} files: {sorted(da)}")

        # 6. every original used once before any is used twice
        first_aug = next((i for i, s in enumerate(samples)
                          if s["split"] == "train" and s["rep"] > 0), None)
        n_orig = plan["n_samples"]["train_originals"]
        check("every original is emitted once before any is emitted twice",
              first_aug is None or first_aug == n_orig,
              f"first augmented sample at position {first_aug} of "
              f"{n_orig} originals")

        # 7. only box-safe ops, and no rotation anywhere
        ops = set()
        for s in samples:
            ops |= set(s["recipe"])
        check("only box-safe augmentation ops appear (no rotation)",
              ops <= set(BOX_SAFE_OPS) and not any("rot" in o for o in ops),
              f"ops used: {sorted(ops)}")

        # 8. the index points at files that exist
        missing = [s["file"] for s in samples[:2000]
                   if not os.path.isfile(os.path.join(plan["root"], s["file"]))]
        check("index paths resolve to real files",
              not missing, f"{len(missing)} missing")

        # 9. classes.json carries index / colour / canonical from class_map
        with open(os.path.join(a, "classes.json")) as f:
            cdoc = json.load(f)
        idx = CM.class_index()
        ok = all(r["index"] == idx[r["name"]]
                 and r["colour"] == CM.colour(r["name"])
                 and r["canonical"] == CM.canonical(r["name"])
                 for r in cdoc["classes"]) and 0 not in idx.values()
        check("classes.json matches class_map (index>=1, colour, canonical)",
              ok, f"{len(cdoc['classes'])} classes, index 0 reserved")

        # 10. --report-only writes nothing
        empty = os.path.join(tmp, "empty")
        build(root, empty, target_per_class, max_repeat, seed, unit,
              report_only=True, verbose=False)
        check("--report-only writes nothing", not os.path.exists(empty))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    n_fail = sum(1 for _n, ok, _d in results if not ok)
    print(f"\nselftest: {len(results) - n_fail}/{len(results)} passed")
    return n_fail == 0


# ------------------------------------------------------------------- main ---

def main():
    ap = argparse.ArgumentParser(
        description="Split-then-balance a COCO damage corpus into a training "
                    "INDEX (no pixels are copied).")
    ap.add_argument("--coco", required=True,
                    help="corpus root; every _annotations.coco.json beneath "
                         "it is pooled and the upstream split is discarded")
    ap.add_argument("--out", default=None,
                    help="output directory for index.jsonl, images.jsonl, "
                         "classes.json, plan.json")
    ap.add_argument("--target-per-class", type=int, default=None,
                    help="per-class target in the train split; default is the "
                         "largest class's real count")
    ap.add_argument("--max-repeat", type=int, default=15,
                    help="hard ceiling on how many times one original may be "
                         "used in train (default 15)")
    ap.add_argument("--unit", choices=("boxes", "images"), default="boxes",
                    help="count the target in annotation boxes (default) or "
                         "in images")
    ap.add_argument("--seed", type=int, default=1337)
    ap.add_argument("--merge-groups", action="store_true",
                    help="fold FINAL_CLASSES into class_map.TRAIN_GROUPS, so "
                         "balance comes from merging related damage rather "
                         "than from 15x cloning of the thin classes")
    ap.add_argument("--train-only-list",
                    help="file of shas (one per line, or jsonl with a 'sha' "
                         "field) barred from valid/test. Images with a "
                         "burned-in label: fine to train on, never to score "
                         "on. See clean_dataset.VERDICT_POLICY.")
    ap.add_argument("--unhealthy-multiplier", type=float,
                    default=UNHEALTHY_MULTIPLIER,
                    help="flag any class needing more than this multiplier "
                         "(default 15)")
    ap.add_argument("--sha-cache", default=None,
                    help="optional JSON cache of file SHAs, for large corpora "
                         "whose COCO has no `sha` field")
    ap.add_argument("--report-only", action="store_true",
                    help="print the plan and write nothing")
    ap.add_argument("--selftest", action="store_true",
                    help="check the split/balance guarantees on --coco")
    args = ap.parse_args()

    if args.selftest:
        ok = selftest(args.coco, args.target_per_class, args.max_repeat,
                      args.seed, args.unit)
        raise SystemExit(0 if ok else 1)

    if not args.report_only and not args.out:
        ap.error("--out is required unless --report-only is given")

    pin = load_train_only(args.train_only_list)
    if pin:
        print(f"train-only pins: {len(pin):,} shas barred from valid/test")

    plan, _samples, _images = build(
        args.coco, args.out, args.target_per_class, args.max_repeat,
        args.seed, args.unit, args.unhealthy_multiplier, args.sha_cache,
        report_only=args.report_only, train_only=pin,
        merge_groups=args.merge_groups)
    print(format_report(plan))
    if args.report_only:
        print("\n--report-only: nothing was written.")
    else:
        print(f"\nwrote index.jsonl images.jsonl classes.json plan.json "
              f"-> {os.path.abspath(args.out)}")


if __name__ == "__main__":
    main()
