"""Tests for reading a drawing's own room schedule.

The schedule is the only independent check the whole pipeline has — Model
Mode compares what it builds against the areas an architect printed, and
until now those had to be typed in by hand.

WHAT THE REAL SHEET TAUGHT, and what this file pins down:

  1. SCRAPING THE PAGE TEXT DOES NOT WORK. pdfplumber returns words in page
     order, and the plan sits beside the table, so a regex over the text
     produced rooms called "13 m2 Bathroom", "204.7 SF Ensuite" and
     "1 : 100 Hallway" — plan labels welded onto schedule rows. Everything
     works inside the table's bounding box for that reason.

  2. THE SAME ROOM NAME REPEATS, LEGITIMATELY. A building has a Hallway on
     every storey, and one first-floor plan carried two rooms both labelled
     "Ensuite". Code that refuses duplicates rejects a valid drawing; code
     that assigns them into a dict by name silently drops one. They are
     summed, which is the rule the other side already uses.

  3. NAMES ARE NOT CORRECTED. A real sheet came back with a room called "we"
     — almost certainly "WC" — and "Bedroom4" with no space. Both are kept
     exactly as printed. A parser that quietly improves the drawing is one
     you can no longer check against it.

fixtures_schedule.pdf is SYNTHETIC, generated by make_fixture.py. The real
drawing is a client's, with an address on it, and this repository is public.
The fixture reproduces every pathology that can be synthesised.

ONE BEHAVIOUR IS NOT COVERED HERE. On the real sheet the grid detector
returned None for the area cell on 8 of 20 rows, which is why areas are
recovered from their coordinates instead. Reproducing that needs the exact
cell geometry a particular CAD exporter emits. Measured on the real drawing:
extract() alone read 12 of 20 rows; with positional recovery, 20 of 20. That
result is recorded here and is not asserted, because asserting it would
require shipping the drawing.

Run: python building/test_schedule.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import schedule as S  # noqa: E402

PASSED, FAILED = [], []


def check(name, cond, detail=""):
    (PASSED if cond else FAILED).append(
        name if cond else f"{name}{' — ' + detail if detail else ''}")


FIXTURE = os.path.join(HERE, "fixtures_schedule.pdf")

try:
    import pdfplumber  # noqa: F401
    HAVE = os.path.exists(FIXTURE)
except ImportError:
    HAVE = False

if not HAVE:
    check("0 skipped — pdfplumber or the fixture is absent", True)
else:
    R = S.parse(FIXTURE)

    # ---- 1. it reads the schedule ------------------------------------------
    check("1a every row is read", len(R["rooms"]) == 11, str(len(R["rooms"])))
    check("1b areas total correctly", R["total_area_m2"] == 147.0,
          str(R["total_area_m2"]))
    check("1c three levels", len(S.levels(R)) == 3)
    check("1d each room carries its level number",
          all(isinstance(r["level_no"], int) for r in R["rooms"]))
    check("1e levels are numbered from the schedule's own ordinals",
          [l["level_no"] for l in S.levels(R)] == [1, 2, 3])
    check("1f and each level totals its own rooms",
          [l["area_m2"] for l in S.levels(R)] == [64.0, 50.0, 33.0],
          str([l["area_m2"] for l in S.levels(R)]))

    # ---- 2. the number and its unit are separate words ---------------------
    # A CAD export writes "34" and "m2" as two tokens with a gap. Reading
    # only tokens that match "34 m2" as one word finds nothing at all.
    check("2a a number is paired with the unit token beside it",
          any(r["area_m2"] == 34.0 for r in R["rooms"]))
    check("2b every room got an area", all(r["area_m2"] > 0 for r in R["rooms"]))

    # ---- 3. plan labels outside the table are ignored -----------------------
    # The fixture puts "Bathroom / 6 m2 / 63.0 SF" and "1 : 100 / Master
    # Bedroom / 15 m2" on the page OUTSIDE the schedule, exactly where the
    # first parser picked them up.
    names = [r["name"] for r in R["rooms"]]
    check("3a a plan label outside the table is not read as a room",
          "Bathroom" not in names, str(names))
    check("3b nor is one that sits beside a scale note",
          "Master Bedroom" not in names)
    check("3c and no room name carries a scale or an imperial area",
          not any("1 :" in n or "SF" in n for n in names), str(names))

    # ---- 4. the title block is not the schedule ----------------------------
    check("4a the smaller table on the page is not chosen",
          all("15.06" not in n for n in names))
    check("4b nor its contents read as rooms", "Scale (@A3)" not in names)

    # ---- 5. repeated names -------------------------------------------------
    halls = [r for r in R["rooms"] if r["name"] == "Hallway"]
    check("5a a Hallway on each of three storeys is three rooms",
          len(halls) == 3, str(len(halls)))
    check("5b kept apart by level, not merged",
          sorted(h["level_no"] for h in halls) == [1, 2, 3])
    check("5c and their areas are not conflated",
          sorted(h["area_m2"] for h in halls) == [9.0, 11.0, 14.0],
          str(sorted(h["area_m2"] for h in halls)))

    ens = [r for r in R["rooms"] if r["name"] == "Ensuite"]
    check("5d two rooms named Ensuite on ONE level are both kept",
          len(ens) == 2, str(len(ens)))
    check("5e and that is warned about, since it is unusual",
          any("more than once on the same level" in w for w in R["warnings"]),
          str(R["warnings"]))

    # ---- 6. handing it to Model Mode ---------------------------------------
    # check_against_schedule works one floor plate at a time. Passing the
    # whole building would compare a ground-floor plan against every room in
    # it and report the upper storeys as missing.
    g = S.as_check_input(R, level_no=1)
    check("6a narrowing to a level drops the other storeys",
          "Bedroom 3" not in g and "Cinema" not in g, str(sorted(g)))
    check("6b and keeps that storey's rooms", g.get("Hallway") == 9.0,
          str(g.get("Hallway")))

    f = S.as_check_input(R, level_no=2)
    # THE BUG THIS EXISTS TO CATCH. Assigning rooms into a dict by name drops
    # one of the two En-suites, and the check then compares two modelled
    # rooms against one stated area — a 100% error on a correct drawing.
    check("6c two rooms sharing a name on one level SUM, they do not overwrite",
          f.get("Ensuite") == 6.0, str(f.get("Ensuite")))
    check("6d which matches how the model side already sums by name",
          f.get("Hallway") == 14.0)
    check("6e the level's rooms all come through",
          len(f) == 4, str(sorted(f)))
    check("6f with no level given, the whole building comes back",
          len(S.as_check_input(R)) >= 5)

    # The two sides agreeing is the whole point: model3d sums its rooms by
    # name for an L-shaped space, so the schedule must sum the same way.
    import model3d as M  # noqa: E402
    rooms = [M.Room("Ensuite", 0, 0, 1.7, 1.8),
             M.Room("Ensuite", 3, 0, 1.7, 1.8)]
    c = M.check_against_schedule(rooms, f)
    row = next(x for x in c["rooms"] if x["room"] == "Ensuite")
    check("6g two modelled en-suites agree with two scheduled ones",
          row["status"] == "agrees", str(row))
    check("6h and the check knows it summed two parts", row.get("parts") == 2)

    # ---- 7. names are reported as printed ----------------------------------
    check("7a a name with no space is not helpfully corrected",
          "Bedroom4" in names, str(names))
    check("7b a name broken across lines is rejoined, not invented",
          any(n.startswith("Kitchen/Dini") for n in names), str(names))

    # ---- 8. failing honestly -----------------------------------------------
    try:
        S.parse(FIXTURE, page_number=99)
        check("8a a page that does not exist is an error, not a guess", False)
    except (S.ScheduleError, IndexError):
        check("8a a page that does not exist is an error, not a guess", True)

    try:
        S.parse(os.path.join(HERE, "schedule.py"))
        check("8b a file that is not a PDF is refused", False)
    except Exception:
        check("8b a file that is not a PDF is refused", True)

    check("8c a level cell that is not a level is skipped, not parsed",
          S.LEVEL.match("Scale (@A3)") is None)
    check("8d while a real one parses", bool(S.LEVEL.match("2. First Floor")))
    check("8e including one with no trailing 'Floor'",
          bool(S.LEVEL.match("3. Loft")))

    check("8f the module does not reach the vehicle worker",
          "trellis" not in open(os.path.join(HERE, "schedule.py")).read().lower())


# ==========================================================================
print()
for f in FAILED:
    print(f"FAIL  {f}")
print(f"\n{len(PASSED)} passed, {len(FAILED)} failed")
sys.exit(1 if FAILED else 0)
